openapi: 3.0.0
info:
  title: My test app apis
  description: my test app apis
  version: "2.0.0"
  contact:
    name: Saifudheen
    email: vksaifudheen4@gmail.com
servers:
  - url: 'https://APIDOMAIN/SWENV'

x-amazon-apigateway-request-validators:
  all:
    validateRequestBody: true
    validateRequestParameters: true
  params:
    validateRequestBody: true
    validateRequestParameters: true
  body:
    validateRequestBody: true
    validateRequestParameters: false

paths:
  '/products':
    get:
      operationId: getProducts
      x-amazon-apigateway-request-validator: all
      x-amazon-apigateway-integration:
        uri: >-
          arn:aws:apigateway:SWREGION:lambda:path/2015-03-31/functions/arn:aws:lambda:SWREGION:829121778091:function:update-products-SWENV/invocations
        passthroughBehavior: when_no_match
        type: aws_proxy
        httpMethod: POST
        timeoutInMillis: 3000
      responses:
        '200':
          description: User Identity Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductResponse'
        '403':
          description: 400 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestResponse'
  '/products':
    post:
      operationId: postProducts
      x-amazon-apigateway-request-validator: all
      x-amazon-apigateway-integration:
        uri: >-
          arn:aws:apigateway:SWREGION:lambda:path/2015-03-31/functions/arn:aws:lambda:SWREGION:829121778091:function:update-products-SWENV/invocations
        passthroughBehavior: when_no_match
        type: aws_proxy
        httpMethod: POST
        timeoutInMillis: 3000
      requestBody:
        description: add new product
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductResponse'
      responses:
        '201':
          description: User Identity Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductResponse'
        '403':
          description: 400 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestResponse'
  '/products':
    patch:
      operationId: patchProducts
      x-amazon-apigateway-request-validator: all
      x-am`azon-apigateway-integration:
        uri: >-
          arn:aws:apigateway:SWREGION:lambda:path/2015-03-31/functions/arn:aws:lambda:SWREGION:829121778091:function:update-products-SWENV/invocations
        passthroughBehavior: when_no_match
        httpMethod: POST
        type: aws_proxy
        timeoutInMillis: 3000
      requestBody:
        description: add new product
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductResponse'
      responses:
        '201':
          description: User Identity Updated
          content:
            application/json:
              schema:
                type: object
        '403':
          description: 400 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestResponse'
  '/products/{id}':
    delete:
      operationId: deleteProducts
      x-amazon-apigateway-request-validator: all
      x-amazon-apigateway-integration:
        uri: >-
          arn:aws:apigateway:SWREGION:lambda:path/2015-03-31/functions/arn:aws:lambda:SWREGION:829121778091:function:update-products-SWENV/invocations
        passthroughBehavior: when_no_match
        httpMethod: POST
        timeoutInMillis: 3000
        type: aws_proxy
        parameters:
          - $ref: '#/components/parameters/id'
      responses:
        '204':
          description: User Identity Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateResponse'
        '403':
          description: 400 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestResponse'

components:
  ProductResponse:
    type: object
    title: get product
    required:
      - productName
      - id
    properties:
      productName:
        type: string
        description: productName
        example: product1
      id:
        type: string
        description: id
        example: "1234"

  UpdateResponse:
    type: object
  
  BadRequestResponse:
    type: object
    properties:
      statusCode:
        type: integer
        example: 400
      responseBody:
        type: string
        example: >-
          The submitted request body does not match the schema specification
          for this request. Please check if all mandatory fields are passed in
          the request body